### ISSUE TITLE
Login not working with "don't keep activities"

### ISSUE THREAD

**Issue by eriksquare** [facebook/facebook-android-sdk#1032]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Java version

1.8.0

### Android version

API26, API 29

### Android SDK version

12.2.0

### Installation platform & version

Gradle 7

### Package

Login

### Goals

Be able to login when activity is recreated

### Expected results

Get the login callbacks as without "don't keep activities"

### Actual results

When going back to the app no callback is invoked. If in this state you background the app and then reopen a crash will happen:

```
2021-12-22 15:41:34.090 8659-8659/com.app.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.app.debug, PID: 8659
    android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.facebook.login.LoginClient$Result
        at android.os.Parcel.readParcelableCreator(Parcel.java:2883)
        at android.os.Parcel.readParcelable(Parcel.java:2809)
        at android.os.Parcel.readValue(Parcel.java:2712)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3081)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
        at android.os.Bundle.getParcelable(Bundle.java:940)
        at android.content.Intent.getParcelableExtra(Intent.java:7485)
        at com.facebook.login.LoginManager.onActivityResult(LoginManager.java:274)
        at com.facebook.login.LoginManager$1.onActivityResult(LoginManager.java:241)
        at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.kt:44)
        at com.facebook.login.LoginManager$AndroidxActivityResultRegistryOwnerStartActivityDelegate$2.onActivityResult(LoginManager.java:1346)
        at com.facebook.login.LoginManager$AndroidxActivityResultRegistryOwnerStartActivityDelegate$2.onActivityResult(LoginManager.java:1343)
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:227)
        at com.facebook.login.LoginManager$AndroidxActivityResultRegistryOwnerStartActivityDelegate.startActivityForResult(LoginManager.java:1328)
        at com.facebook.login.LoginManager.tryFacebookActivity(LoginManager.java:1112)
        at com.facebook.login.LoginManager.startLogin(LoginManager.java:1037)
        at com.facebook.login.LoginManager.logIn(LoginManager.java:873)
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:587)
        at com.facebook.login.LoginManager.logInWithReadPermissions(LoginManager.java:529)
        at com.app.login.framework.SocialLoginUtilityKt.startFacebookSignIn(SocialLoginUtility.kt:156)
        at com.app.login.presentation.login.LoginFragment$onInitObservers$3.invoke(LoginFragment.kt:225)
        at com.app.login.presentation.login.LoginFragment$onInitObservers$3.invoke(LoginFragment.kt:221)
        at com.app.androidutility.EventObserver.onChanged(SingleEvent.kt:47)
        at com.com.app.androidutility.EventObserver.onChanged(SingleEvent.kt:44)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

### Steps to reproduce

- enable "don't keep activities" in phone debug options
- try to login using LoginManager
- no callback is received
- when going in background then foreground again and retrying a crash will happen

### Code samples & details

```java
override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        //do login-signUp
        with(LoginManager.getInstance()) {

            registerCallback(
                facebookCallBackManager,
                object : FacebookCallback<LoginResult> {
                    override fun onSuccess(loginResult: LoginResult) {
                        //won't get here
                        val fbToken = loginResult.accessToken.token
                    }

                    override fun onCancel() {
                        //won't get here
                    }

                    override fun onError(exception: FacebookException) {
                        //won't get here
                    }
                })
            logInWithReadPermissions(this@LoginFragment, facebookCallBackManager, listOf("email"))
        }
    }
```

**Comment by linmx0130** [comment]
Hi @eriksquare! Thanks for raising this issue! However, we cannot reproduce this bug. In order to learn more details to help us to understand what's happening, could you answer following questions?
1. Which version of Facebook App you're using for the login procedure? Or is it through custom tabs? 
2. Did you use ProGuard/R8 optimization? It seems that `com.facebook.login.LoginClient$Result` is deleted in the compiled app.

**Comment by eriksquare** [comment]
The issue happens 
- every time with custom tabs
- with app version 348.0.0.39.118 only when Facebook app was freshly installed

I've tried my app both in debug and in release mode with and without minify enabled with the same results

**Comment by linmx0130** [comment]
Hi @eriksquare! Thank you again for reporting this issue! We still cannot reproduce the bug but according to your description I have a try to fix it by setting the class loader (see 36fe3889c99dc306c6f2c4ea4f7cd82974d45045) before parsing the login result. This patch will be shipped in v12.3.0. We will release the new version next week so that you can have a test to verify whether it solves the problem.

**Comment by linmx0130** [comment]
Hi @eriksquare! We just released v12.3.0 to have the bug fix patch. Could you help us to test whether it solves your problem? Thanks a lot!

**Comment by eriksquare** [comment]
Yes this actually solves the crash issue!

I still don't reliably receive the callbacks from the custom tabs (while from the app works quite good), when i login from there nothing happens. 
Press again the login button and this time will work without opening custom tabs since it is actually already logged in.

**Comment by linmx0130** [comment]
Hi @eriksquare! Great thanks for the update!
I will loop in the owner of the custom tab login feature to confirm the problem on callbacks. For the issue progress tracking reason, I will close this issue but feel free to raise the specific issue on custom tabs callback problem if you find a reliable method to reproduce it.
Thank you again for your contribution to Facebook Android SDK!
