### ISSUE TITLE
Share action is success but return UnknownError in facebook sdk 12.0.0+

### ISSUE THREAD

**Issue by zii4914** [facebook/facebook-android-sdk#1043]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [Github issues](https://github.com/facebook/facebook-android-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Java version

1.8

### Android version

API31,API30

### Android SDK version

12.3.0

### Installation platform & version

Gradle

### Package

Share

### Goals

I use share dialog. It call Facebook app share dialog normally and share success in my facebook account , but return FacebookCallback.onError with UnknownError. I cant found any valuable message in the error.
I both try share in android 11 and android 12, return same error. It is share success and return FacebookCallback.onSuccess when i set facebook share sdk to version 11.3.0. But it is same error happen when i set sdk version 12.0.0.

### Expected results

Share is success and call FacebookCallback.onSuccess.

### Actual results

Share is success but call FacebookCallback.onError.

### Code samples & details

```java
// share dialog
ShareLinkContent.Builder fbShareLinkContentBuilder = new ShareLinkContent.Builder()
        .setContentUrl(shareLinkContent.getContentUri())
        .setPeopleIds(shareLinkContent.getPeopleIds())
        .setPlaceId(shareLinkContent.getPlaceId())
        .setRef(shareLinkContent.getRef());
fbShareLinkContentBuilder.setQuote(shareLinkContent.getContentDescription());
ShareLinkContent fbShareLinkContent = fbShareLinkContentBuilder.build();
mFBShareDialog.show(fbShareLinkContent);

//FacebookException message
Throwable:UnknownError
        at com.facebook.share.internal.ShareInternalUtility$1.onSuccess(ShareInternalUtility.java:192)
        at com.facebook.share.internal.ShareInternalUtility.handleActivityResult(ShareInternalUtility.java:173)
        at com.facebook.share.internal.ShareInternalUtility$3.onActivityResult(ShareInternalUtility.java:253)
        at com.facebook.internal.CallbackManagerImpl.onActivityResult(CallbackManagerImpl.kt:45)
        at com.facebook.internal.DialogPresenter$startActivityForResultWithAndroidX$2.onActivityResult(DialogPresenter.kt:123)
        at com.facebook.internal.DialogPresenter$startActivityForResultWithAndroidX$2.onActivityResult(DialogPresenter.kt:61)
        at androidx.activity.result.ActivityResultRegistry.doDispatch(ActivityResultRegistry.java:362)
        at androidx.activity.result.ActivityResultRegistry.dispatchResult(ActivityResultRegistry.java:322)
        at androidx.activity.ComponentActivity.onActivityResult(ComponentActivity.java:634)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
        at com.x.x.x.x.FBShareActivity.onActivityResult(FBShareActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:8310)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5002)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5050)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7660)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by linmx0130** [comment]
Hi @zii4914! Thanks for raising the issue! I have confirmed the root cause and the bug fix will be released soon in v13.0. For now you can downgrade to v12.2.0 to address the issue.

**Comment by linmx0130** [comment]
The bug fix is committed as 6533f9f916f1fca17d7e4bd27efbb8092fa9e49f. We will release it in v13.0. The estimated releasing date is Febuary 22, 2022.

**Comment by winniehx** [comment]
> The bug fix is committed as [6533f9f](https://github.com/facebook/facebook-android-sdk/commit/6533f9f916f1fca17d7e4bd27efbb8092fa9e49f). We will release it in v13.0. The estimated releasing date is Febuary 22, 2022.

This problem still occurs in the current version. The sharing action is successful, but the postid is still empty. According to the modified logic, onerror is still displayed.
