### ISSUE TITLE
Auto app event logging feature make UI performance down

### ISSUE THREAD

**Issue by TaQuangTu** [facebook/facebook-android-sdk#748]
## Checklist

- [x] I've updated to the latest released version of the SDK
- [x] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-android-sdk/issues)
- [x] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [x] I've read the [Code of Conduct](CODE_OF_CONDUCT.md)
- [ ] This issue is not security related and can safely be disclosed publicly on GitHub

## Environment
- Java Version: `1.8`
- Android SDK Version: `Android 10` (API level 29).
- Installation Platform & Verison: `Maven`,`Gradle`,`Manual`.

## Goals

I want to use Facebook sdk's app event auto logging feature but keep app UI smooth when app resumes.

## Expected Results

Keep UI performance from lagging when activity resume multiple times while using Auto app event logging feature.

## Actual Results

Activities become lag (UI performance down) when app resume about 2 or more times when I enable auto logging feature in Manifest file:
```
<meta-data android:name="com.facebook.sdk.AutoLogAppEventsEnabled"
            android:value="true"/>
```
How do I use app event auto logging feature but keep the UI performance? Or some ways to fix the lagging issue? 

Thank you!

**Comment by Oliverccccct** [comment]
Hi,
In most cases, the SDK logs app events on Worker Thread but not UI Thread. Could you tell us the SDK version you are using and if can, could you provide us the screenshot of performance change in Android Profiler? Here is the link of how to use Android Profiler: https://developer.android.com/studio/profile/android-profiler
Thanks!

**Comment by Robot2037** [comment]
Hello.
I have the very same issue since FB SDK version 5. Last ok version was 4.41.0 for me. I currently use **FB SDK 6.5.0**, while the issue is still present!

If activity is paused and resumed several times, it became janky. Most noticeable in activities with RecyclerView, ViewPager etc., where you can scroll someting. Android version doesn't matter, I tested it on Android API 16 to 29.

I created simple activity with RecyclerView containing one cell type. When activity is launched, scroll is very smooth without any problems. After that I invoked onPause/onResume in this activity ten times, by opening another acitivity and goind back, and RecyclerView became super junky when scrolling. Even more and more if you pause/resume more times.

I visually measured performance using built-in GPU Renedring and results are following:

**When RecyclerView is scrolled for the first time Activity is opened**
<img src="https://user-images.githubusercontent.com/19485976/80092108-7f76c200-8562-11ea-9504-27ef3e4b7235.png" height="240">

**When RecyclerView is scrolled when Activity onPause-onResume was called 10 times**
<img src="https://user-images.githubusercontent.com/19485976/80092599-5571cf80-8563-11ea-867e-032eb9c55391.png" height="240">

Now comes the funny part. If I turn off FBSDK auto-logging, as mentioned, or if I downgrade to FB SDK 4.41.0, this doen't happen and everything works even if I invoke onPause/onResume 100 times.

On the other hand, this must be some specific combination issue, because I don't see it in our other apps which uses the same FB SDK and share the same code, libraries etc. Even if I copied the Test Activity 1:1 to different app, this doesn't happen. I can't figure it out.

**Comment by TaQuangTu** [comment]
> Hi,
> In most cases, the SDK logs app events on Worker Thread but not UI Thread. Could you tell us the SDK version you are using and if can, could you provide us the screenshot of performance change in Android Profiler? Here is the link of how to use Android Profiler: https://developer.android.com/studio/profile/android-profiler
> Thanks!

Thank for your reply, @Robot2037 's comment describes exactly the issue I have met. I have tried with sdk version 5.0.0 and later but the issue still appears. When I degrade version of the SDK to 4.27.0 then the issue is no longer appears and UI becomes smooth when app resumes multiple times.

**Comment by poooower** [comment]
We have similar issue, we investigate that
AppEventsLogger.logEvent will call the AddressFilterManager.shouldFilterKey every time,
The execution of ModelManager.predict in shouldFilterKey is very time-consuming (about
200ms, maybe different in different performance phone), so if logEvent is called in the main thread，will causes the user interface to be particularly bad performance.

what's more, we found ModelManager.predict is controlled by server configuration,  some model files, will be downloaded from server when SDK initialize,  and saved at local for using in future.  
So we didn't found this problem when develop,  and we run normally for months. The problem break out recently, influent all user.

**Comment by joesus** [comment]
I believe this was fixed in v6.5.1. @Oliverccccct are you able to confirm?

**Comment by Robot2037** [comment]
No, this issue still happens in v6.5.1 for me. I had to turn off automatic logging in manifest. That was the only that helped so far.

**Comment by yurik94** [comment]
Issue still present in **7.1.0 version**
Currently we have an app shipped with:
`com.facebook.android:facebook-core:5.5.1`

Our internal marketer enabled tracking app events (by using the codeless panel) **without any touch any line of code**, after a few hours all our Android apps started to lagging when scrolling on a RecyclerView which was fine before.

I also increased facebook-core to 7.1.0 but the issue still occurs: the app is laggy and unusable!

As stated from @Robot2037  by changing the fb_app_id to a test version (without codeless events tracking) the app works flawlessy.

Of course we removed all events from codeless tracking but the situation is still crappy.

**Comment by Excuta** [comment]
We are integrating with Version 8.1.0 and the issue still persists. Also with this version, disabling AutoLogAppEvents doesn't fix the issue. We actually need event logging from the SDK.

Also the issue is related to this https://github.com/facebook/facebook-android-sdk/issues/618

is there any updates regarding this?

**Comment by vaibhav2ghadge** [comment]
> We have similar issue, we investigate that
> AppEventsLogger.logEvent will call the AddressFilterManager.shouldFilterKey every time,
> The execution of ModelManager.predict in shouldFilterKey is very time-consuming (about
> 200ms, maybe different in different performance phone), so if logEvent is called in the main thread，will causes the user interface to be particularly bad performance.
> 
> what's more, we found ModelManager.predict is controlled by server configuration, some model files, will be downloaded from server when SDK initialize, and saved at local for using in future.
> So we didn't found this problem when develop, and we run normally for months. The problem break out recently, influent all user.
> 
> Due to the network conditions, the user app upgrade is very slow, so most users are still suffering from this problem, we hope the SDK Server can roll back the relevant model configuration as soon as possible to solve the problem.

How did you solve this problem? can you guide us.

**Comment by hiddow** [comment]
SDK 12.1.0 also have this problem!!!!!!!!!!

**Comment by hiddow** [comment]
i found a solution： just add CodelessManager.disable() fun in yout mainactivity onCreate() method, this fun will disable codeless
